version: "3.7"

services:
  mysql:
    image: mysql:8.0
    container_name: mysqlserver
    hostname: mysqlserver
    ports:
      - 3305:3306
    environment: 
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./database/meet-me_dump.sql:/docker-entrypoint-initdb.d/meet-me_dump.sql
  
  
  app:
    image: payara/server-full
    container_name: payaraweb
    hostname: payaraweb
    ports:
      - 8080:8080
    volumes:
      - ./target/MeetMe-5.13.war:/opt/payara/deployments/MeetMe-5.13.war

